version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-mhc
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/grafana/csv
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource,yesoreyeram-infinity-datasource
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=marcusolsson-csv-datasource
      - GF_PLUGIN_MARCUSOLSSON_CSV_DATASOURCE_ALLOW_LOCAL_MODE=true
    restart: unless-stopped

  csv-server:
    image: python:3.9-slim
    container_name: csv-server
    volumes:
      - ./data:/data
    command: python -m http.server 8080 --directory /data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  grafana-storage: